### ISSUE TITLE
Paired end reads feature

### ISSUE THREAD

**Issue by Sanrrone** [FofanovLab/mtsv_tools#10]
Dears,
Is it possible to execute the binner command on paired end reads? or they must be merged in just one file?
thanks in advance!

**Comment by tfursten** [comment]
Hello and thanks for reaching out about this issue.
Currently the binner command only accepts a single read file as input. To run paired end reads you can 
1) Merge both ends into one file
2) Run each file through the binner separately and then use the merge command to combine the output.

We may add a multiple input file feature in the future, but we prefer running the files individually through the computational bottleneck and then have the option to combine them in different ways afterward.

**Comment by Sanrrone** [comment]
Understood, could you also add the feature to accept .gz files? as many users works with hundred of files that feature could help us a lot!.

thanks!
